<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:kernel="http://www.modelexecution.org/xmof/syntax/classes/mykernel"
    name="petrinetConfiguration" nsURI="http://petrinet/1.0/configuration"
    nsPrefix="petrinetConf">
  <eClassifiers xsi:type="kernel:BehavioredEClass" name="NetConfiguration" eSuperTypes="http://petrinet/1.0#//Net">
    <eOperations xsi:type="kernel:BehavioredEOperation" name="main"/>
    <eOperations xsi:type="kernel:BehavioredEOperation" name="run">
      <eAnnotations source="http://www.modelexecution.org/xmof">
        <details key="Step" value="true"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="kernel:BehavioredEClass" name="PlaceConfiguration" eSuperTypes="http://petrinet/1.0#//Place">
    <eOperations xsi:type="kernel:BehavioredEOperation" name="removeToken"/>
    <eOperations xsi:type="kernel:BehavioredEOperation" name="addToken"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokens" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="kernel:BehavioredEClass" name="TransitionConfiguration"
      eSuperTypes="http://petrinet/1.0#//Transition">
    <eOperations xsi:type="kernel:BehavioredEOperation" name="isEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations xsi:type="kernel:BehavioredEOperation" name="fire">
      <eAnnotations source="http://www.modelexecution.org/xmof">
        <details key="Step" value="true"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
