<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iml" nsURI="http://sequentialiml/iml/" nsPrefix="iml">
  <eClassifiers xsi:type="ecore:EClass" name="IdentifyableElement" abstract="true" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header" eSuperTypes="//IdentifyableElement">
    <eOperations name="initializeModel">
      <eAnnotations source="aspect"/>
      <eParameters name="args" upperBound="-1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="getCurrentStates" eType="//Iterable">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1" eType="//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddData" eSuperTypes="//IdentifyableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="//IdentifyableElement //ConnectionPoint">
    <eOperations name="activate">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="deactivate">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="executeActivities">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="init">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminal">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1" eType="//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="current">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateTransition" eSuperTypes="//IdentifyableElement //ConnectionPoint">
    <eOperations name="isEnabled">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="doFire">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booleanGuard" eType="//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventGuard" eType="//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Jump" eSuperTypes="//IdentifyableElement //ConnectionPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="//IdentifyableElement">
    <eOperations name="execute">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="doExecute">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="init">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminal">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firedEvents" upperBound="-1" eType="//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" eType="//Time" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="current">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="//IdentifyableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SIUnit">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimultaneousDivergence" eSuperTypes="//IdentifyableElement //ConnectionPoint">
    <eOperations name="isEnabled">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="doFire">
      <eAnnotations source="aspect"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimultaneousConvergence" eSuperTypes="//IdentifyableElement //ConnectionPoint">
    <eOperations name="isEnabled">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="doFire">
      <eAnnotations source="aspect"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionDivergence" eSuperTypes="//IdentifyableElement //ConnectionPoint">
    <eOperations name="isEnabled">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="doFire">
      <eAnnotations source="aspect"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionConvergence" eSuperTypes="//IdentifyableElement //ConnectionPoint">
    <eOperations name="isEnabled">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="doFire">
      <eAnnotations source="aspect"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionPoint" abstract="true">
    <eOperations name="isEnabled">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="fire">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="doFire">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="getPredecessors" eType="//Iterable">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="getSuccessors" eType="//Iterable">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="getSource" eType="//ConnectionPoint">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="getTarget" eType="//ConnectionPoint">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firing">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="//IdentifyableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//ConnectionPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//ConnectionPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Time">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="earliestStart">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latestStart">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="earliestEnd">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latestEnd">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Iterable" instanceClassName="java.lang.Iterable">
    <eAnnotations source="aspect"/>
  </eClassifiers>
</ecore:EPackage>
