<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:kernel="http://www.modelexecution.org/xmof/syntax/classes/mykernel"
    name="petrinet2Configuration" nsURI="http://petrinet2/1.0/configuration"
    nsPrefix="petrinetConf">
  <eClassifiers xsi:type="kernel:BehavioredEClass" name="NetConfiguration" eSuperTypes="../../org.modelexecution.xmof.examples.petrinet2/model/petrinet2.ecore#//Net">
    <eOperations xsi:type="kernel:BehavioredEOperation" name="run"/>
    <eOperations xsi:type="kernel:BehavioredEOperation" name="main">
      <eParameters name="initialTokens" upperBound="-1" eType="#//Token"/>
    </eOperations>
    <eOperations xsi:type="kernel:BehavioredEOperation" name="initializeMarking">
      <eParameters name="initialTokens" upperBound="-1" eType="#//Token"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="kernel:BehavioredEClass" name="PlaceConfiguration" eSuperTypes="../../org.modelexecution.xmof.examples.petrinet2/model/petrinet2.ecore#//Place">
    <eOperations xsi:type="kernel:BehavioredEOperation" name="addToken"/>
    <eOperations xsi:type="kernel:BehavioredEOperation" name="removeToken"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heldTokens" upperBound="-1"
        eType="#//Token" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="kernel:BehavioredEClass" name="TransitionConfiguration"
      eSuperTypes="../../org.modelexecution.xmof.examples.petrinet2/model/petrinet2.ecore#//Transition">
    <eOperations xsi:type="kernel:BehavioredEOperation" name="fire"/>
    <eOperations xsi:type="kernel:BehavioredEOperation" name="isEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TokenDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialTokens" upperBound="-1"
        eType="#//Token" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token">
    <eStructuralFeatures xsi:type="ecore:EReference" name="holdingPlace" lowerBound="1"
        eType="ecore:EClass ../../org.modelexecution.xmof.examples.petrinet2/model/petrinet2.ecore#//Place"/>
  </eClassifiers>
</ecore:EPackage>
